version: "2"

services:
  amqp:
    container_name: ${AMQP_STATS_CONTAINER_NAME}${SERVICE_GROUP}
    image: ${AMQP_STATS_DOCKER_IMAGE}:${AMQP_STATS_DOCKER_TAG}
    restart: unless-stopped
    volumes:
      - ${MEDIA_PATH}:/data/sighthound/media:rw
      - ${LOG_PATH}:/data/sighthound/logs/mcp:rw
    env_file:
      - .env
    networks:
      core_sighthound:
        aliases:
          - ${AMQP_STATS_CONTAINER_NAME}${SERVICE_GROUP}

networks:
  core_sighthound:
    external: true