version: "2"

services:  
  live555:
    container_name: ${LIVE555_CONTAINER_NAME}${SERVICE_GROUP}
    image: ${LIVE555_DOCKER_IMAGE}:${LIVE555_DOCKER_TAG}
    restart: unless-stopped
    ports:
      - "7554:554"
    volumes:
      - ./test-data:/mnt
    networks:
      core_sighthound:
        aliases:
          - ${LIVE555_CONTAINER_NAME}${SERVICE_GROUP}

networks:
  core_sighthound:
    external: true
      