version: "2"

services:
  influxdb:
    image: influxdb:2.0.7
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${MCP_INFLUXDB_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${MCP_INFLUXDB_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: sighthound
      DOCKER_INFLUXDB_INIT_BUCKET: mcp
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${MCP_INFLUXDB_TOKEN}
    volumes:
      - influxdb-persistent:/var/lib/influxdb
      - influxdb-persistent-2:/var/lib/influxdb2
    ports:
    - "8086:8086"
    networks:
      - core_sighthound

  mcp:
    image: ${MCP_DOCKER_IMAGE}:${MCP_DOCKER_TAG}
    restart: unless-stopped
    depends_on:
      - influxdb
    volumes:
      - ${MEDIA_PATH}:/data/sighthound/media:rw
      - ./conf/mcp.yml:/etc/mcpd/default.json:ro
    ports:
      - "8089:8088"
    env_file:
      - .env
    networks:
      - core_sighthound

networks:
  core_sighthound:
    external: true

volumes:
  influxdb-persistent:
  influxdb-persistent-2:
