version: "3"
services:

  analytics:
    image: us-central1-docker.pkg.dev/ext-edge-analytics/docker/sio:${SIO_RELEASE-r231204}${SIO_DOCKER_TAG_VARIANT}
    restart: unless-stopped
    environment:
      # Location where SIO will place generated model engine files
      - SIO_DATA_DIR=/data/sio-cache
    # Container runtime defaults to `runc` if SIO_DOCKER_RUNTIME not set. Use `nvidia` if GPU is installed.
    runtime: ${SIO_DOCKER_RUNTIME-runc}
    volumes:
      # Read-only shared folder for data exchange with host / other containers.
      # We'll use it for license, config files, etc.
      - ./config:/config:ro
      # Writable shared folder for data exchange with host
      # We'll use it for storing the generated model files, data exchange folder, etc.
      - ./data:/data
      # Shared memory-backed folder for data exchange with other containers
      - run_vol:/tmp/inputFiles
    entrypoint:
      - /sighthound/sio/bin/runPipelineSet
      # Pipeline configuration file
      - /config/analytics/pipelines.json
      # License at the path accessible in the container
      - --license-path=/config/sighthound-license.json
      # Log level (info, debug, trace)
      - --log=${SIO_LOG_LEVEL-info}

  gateway:
    image: us-central1-docker.pkg.dev/ext-edge-analytics/docker/rest-api-gateway:latest
    restart: unless-stopped
    environment:
      - CLOUDVX_LOG_FILE=/data/logs/cloudvx.log
      # Log level (error, info, debug)
      - CLOUDVX_LOG_LEVEL=info
    ports:
      - "8383:8080"
    volumes:
      # Overrides default config
      - ./config/gateway/service.json:/cloudvx/config/local.json:ro
      # Writable shared folder for data exchange with host
      - ./data:/data
      # Shared memory-backed folder for data exchange with other containers
      - run_vol:/tmp/inputFiles
    depends_on:
      - analytics

  # UI demo avialable at http://localhost:8484
  # Remove this service in production.
  ui-demo:
    image: us-central1-docker.pkg.dev/ext-edge-analytics/docker/rest-api-gateway-ui-demo:latest
    restart: unless-stopped
    ports:
      - "8484:80"
    depends_on:
      - gateway

# Use tmpfs for data exchange between the two containers
volumes:
  run_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
